version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: shared_db
    volumes:
      - ./shared/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    volumes:
      - ./shared/redis/data:/data
    ports:
      - "6379:6379"

  usermanagementmodule:
    build:
      context: ./userManagementModule
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=shared_db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=mysecretpassword

#  blogmanagementmodule:
#    build:
#      context: ./blogManagementModule
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3306
#      - MYSQL_DATABASE=shared_db
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=mysecretpassword
#
#  paymentmodule:
#    build:
#      context: ./paymentModule
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8080"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3306
#      - MYSQL_DATABASE=shared_db
#      - MYSQL_USERNAME=root
#      - MYSQL_PASSWORD=mysecretpassword
